{% set name = "aws-checksums" %}
{% set version = "0.2.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/awslabs/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: cb6509f75e42ee25c372a6d379e8582ce5179e5335183842e808f7d8abb0c314

build:
  number: 0
  run_exports:
    - {{ pin_subpackage("aws-checksums", max_pin="x.x.x") }}

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - cmake >=3.9
    - ninja-base
  host:
    - aws-c-common 0.12.6

test:
  commands:
    - test -f $PREFIX/lib/libaws-checksums${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/include/aws/checksums/exports.h  # [unix]
    - if not exist %LIBRARY_BIN%\aws-checksums.dll exit 1  # [win]
    - if not exist %LIBRARY_INC%\aws\checksums\exports.h exit 1  # [win]

about:
  home: https://github.com/awslabs/aws-checksums
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Cross-Platform HW accelerated CRC32c and CRC32 with fallback to efficient SW implementations. C interface with language bindings for each of our SDKs.
  description: Cross-Platform HW accelerated CRC32c and CRC32 with fallback to efficient SW implementations. C interface with language bindings for each of our SDKs.
  dev_url: https://github.com/awslabs/aws-checksums
  doc_url: https://github.com/awslabs/aws-checksums

extra:
  recipe-maintainers:
    - xhochy