{% set name = "aws-checksums" %}
{% set version = "0.2.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/awslabs/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 178e8398d98111f29150f7813a70c20ad97ab30be0de02525440355fe84ccb1d

build:
  number: 0
  run_exports:
    - {{ pin_subpackage("aws-checksums", max_pin="x.x.x") }}

requirements:
  build:
    - cmake >=3.9
    - {{ compiler('c') }}
    - ninja-base
  host:
    - aws-c-common 0.12.3

test:
  commands:
    - test -f $PREFIX/lib/libaws-checksums${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/include/aws/checksums/exports.h  # [unix]
    - if not exist %PREFIX%\\Library\\bin\\aws-checksums.dll exit 1  # [win]
    - if not exist %PREFIX%\\Library\\include\\aws\\checksums\\exports.h exit 1  # [win]

about:
  home: https://github.com/awslabs/aws-checksums
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Cross-Platform HW accelerated CRC32c and CRC32 with fallback to efficient SW implementations. C interface with language bindings for each of our SDKs.
  description: Cross-Platform HW accelerated CRC32c and CRC32 with fallback to efficient SW implementations. C interface with language bindings for each of our SDKs.
  dev_url: https://github.com/awslabs/aws-checksums
  doc_url: https://github.com/awslabs/aws-checksums

extra:
  recipe-maintainers:
    - xhochy